=== mc17uulm/wp-builder/wp-builder.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,3}$"
    },
    "type": {
      "type": "string"
    },
    "author": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        }
      },
      "required": ["name", "email"],
      "additionalProperties": false
    },
    "build": {
      "type": "object",
      "properties": {
        "includes": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string"
              }, {
                "type": "object",
                "patternProperties": {
                  ".{1,}": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        }
      },
      "required": ["includes"],
      "additionalProperties": false
    }
  },
  "required": ["name", "slug", "version"],
  "additionalProperties": false
}

=== mc17uulm/wp-builder/wp-builder.json
{
  "name": "WPReminder",
  "slug": "wp-reminder",
  "version": "0.1.0",
  "type": "plugin",
  "author": {
    "name": "CodeLeaf",
    "email": "plugins@code-leaf.de"
  },
  "build": {
    "includes": [
      "dist/fonts",
      "dist/css",
      {"dist/js/*.js": "dist/js"},
      {"dist/js/*.php": "dist/js"},
      "languages",
      "plugin",
      "schemas",
      "composer.json",
      "composer.lock",
      "wp-reminder.php"
    ]
  }
}
